server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eric?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhou123
    driver: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html   
      
mybatis:
  mapper-locations: 'classpath:mybatis/mapping/**.xml'
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.zx.entity

logging:
  level:
    eric.app1.module.mapper: DEBUG
    eric: INFO